name: animeapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/animeicon.png"
  min_sdk_android: 24


flutter:
  uses-material-design: true
  assets:
      - assets/icon/
